# Python Assignment
Topic: 3D Arrays and Dictionaries


# Part A – 3D Arrays  

# Question 1  
## Create the following 3D array.

Layer 1

[1, 2, 3]
[4, 5, 6]

Layer 2

[7, 8, 9]
[10, 11, 12]

In [ ]:
Write a Python program to:

Print the complete 3D array.
Print the first layer.
Print the second row of the second layer.
Print the element 11.

In [10]:
import numpy as np

arr = np. array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
    [7,8,9],
    [10,11,12]
    ]
])
print("Complete 3D array\n",arr)
print("first layer:\n",arr[0,:,:])
print("Second row of second layer:\n", arr[1,1,:])
print("Second element in row 2 layer 2:\n", arr[-1,-1,-2])


Complete 3D array
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
first layer:
 [[1 2 3]
 [4 5 6]]
Second row of second layer:
 [10 11 12]
Second element in row 2 layer 2:
 11


# Question 2  

Using the same 3D array, reverse the order of layers.

Expected Output

Layer 2

[7, 8, 9]
[10,11,12]

Layer 1

[1,2,3]
[4,5,6]

In [16]:
print("Reverse layer order:\n", arr[::-1,:,:])
print("Reverse layer order:\n", np.flipud(arr))


Reverse layer order:
 [[[ 7  8  9]
  [10 11 12]]

 [[ 1  2  3]
  [ 4  5  6]]]
Reverse layer order:
 [[[ 7  8  9]
  [10 11 12]]

 [[ 1  2  3]
  [ 4  5  6]]]


# Question 3  

##  Reverse every row inside every layer.

Expected Output

In [19]:
print ("Actual array:\n", arr)
print("reverse every row inside every layer:\n", arr[:,::-1,:])

Actual array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
reverse every row inside every layer:
 [[[ 4  5  6]
  [ 1  2  3]]

 [[10 11 12]
  [ 7  8  9]]]


# Question 4  

Completely reverse the entire 3D array by reversing:

    the order of layers,
    the order of rows inside each layer,
    the elements inside every row.

Expected Output

[12,11,10]
[9,8,7]
[6,5,4]
[3,2,1]

In [22]:
print("Actual array:\n",arr)
print("Reverse the order of layer, order of rows, elements:\n",arr[::-1,::-1,::-1])


Actual array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Reverse the order of layer, order of rows, elements:
 [[[12 11 10]
  [ 9  8  7]]

 [[ 6  5  4]
  [ 3  2  1]]]


# Part B – Dictionaries

In [ ]:
# Create a dictionary to store the following student details.

| Key        | Value   |
| ---------- | ------- |
| Roll No    | 101     |
| Name       | Alice   |
| Age        | 20      |
| Department | AI & DS |
| CGPA       | 8.9     |

Display all the information. (use print)

In [35]:
student = {"Roll no":101, "Name":"Alice", "Age":20, "Department":"AI & DS", "CGPA":8.9}
print(student)


{'Roll no': 101, 'Name': 'Alice', 'Age': 20, 'Department': 'AI & DS', 'CGPA': 8.9}


In [ ]:
# Question 6  

Using the dictionary created above,

    Update the CGPA to 9.2
    Add a new key named City with value Chennai
    Display the updated dictionary.

In [37]:

student["CGPA"] = 9.2
student["City"]="Chennai"
print(student)


{'Roll no': 101, 'Name': 'Alice', 'Age': 20, 'Department': 'AI & DS', 'CGPA': 9.2, 'City': 'Chennai'}


In [ ]:
# Question 7  

Write a program to print

    all keys
    all values
    all key-value pairs

using appropriate dictionary methods.

In [72]:
print(student)
#method 1
print(student.keys())
print(list(student.keys()))
#method 2
for key in student:
    print(key)
#method 3
key_list= [key for key in student]
print(key_list)
#method 1
print(list(student.values()))
#method 2
for value in student.values():
    print(value)
for key in student:
    print(student.get(key))
#method 1
for key in student:
    print(key,":",student.get(key))
#method 2
for key, value in student.items():
    print(f"{key}:{value}")
#method3
print(student.items())
print(list(student.items()))

{'Roll no': 101, 'Name': 'Alice', 'Age': 20, 'Department': 'AI & DS', 'CGPA': 9.2, 'City': 'Chennai'}
dict_keys(['Roll no', 'Name', 'Age', 'Department', 'CGPA', 'City'])
['Roll no', 'Name', 'Age', 'Department', 'CGPA', 'City']
Roll no
Name
Age
Department
CGPA
City
['Roll no', 'Name', 'Age', 'Department', 'CGPA', 'City']
[101, 'Alice', 20, 'AI & DS', 9.2, 'Chennai']
101
Alice
20
AI & DS
9.2
Chennai
101
Alice
20
AI & DS
9.2
Chennai
Roll no : 101
Name : Alice
Age : 20
Department : AI & DS
CGPA : 9.2
City : Chennai
Roll no:101
Name:Alice
Age:20
Department:AI & DS
CGPA:9.2
City:Chennai
dict_items([('Roll no', 101), ('Name', 'Alice'), ('Age', 20), ('Department', 'AI & DS'), ('CGPA', 9.2), ('City', 'Chennai')])
[('Roll no', 101), ('Name', 'Alice'), ('Age', 20), ('Department', 'AI & DS'), ('CGPA', 9.2), ('City', 'Chennai')]


In [ ]:
# Question 8  

Create the following nested dictionary.

students = {
    "Student1": {
        "Name": "John",
        "Age": 22
    },
    "Student2": {
        "Name": "Alice",
        "Age": 21
    },
    "Student3": {
        "Name": "David",
        "Age": 20
    }
}

Write a program to

    Print the name of Student2.
    Print the age of Student3.
    Display all student names using a loop.

In [87]:
students ={
    "student1":{
        "Name":"John",
        "Age":22
    },
    "student2":{
        "Name":"Alice",
        "Age":21
    },
    "student3":{
    "Name":"David",
    "Age":20
    }
}
print("Name of student2:",students['student2']['Name'])
print("Age of student3:",students['student3']['Age'])
print("Name of all students:")

for d in students.values():
    name=d.get("Name")
    print(name)
    #print (d['Name'])
    


Name of student2: Alice
Age of student3: 20
Name of all students:
John
Alice
David


In [ ]:
# Question 9  

Create a dictionary of five products.

Example

    Laptop
    Mouse
    Keyboard
    Monitor
    Printer

Each product should contain

    Product Name
    Price
    Quantity

Write a program to

    Display all products.
    Print the product with the highest price.
    Calculate the total inventory value

(Formula:  Inventory Value = Price × Quantity)

In [50]:
product ={
     "laptop":{
        "product name":"hp",
        "price": 22000,
        "quantity": 5
    },
    "mouse":{
        "product name": "zebronics",
        "price":2500,
        "quantity":8
    },
    "keyboard":{
        "product name": "lenova",
        "price":3500,
        "quantity":4
    },
    "monitor":{
        "product name": "ausus",
        "price":6500,
        "quantity":3
    },
    "printer":{
        "product name": "epson",
        "price":12000,
        "quantity":2
    }
}
for key, value in product.items():
    print(f"{key}:{value}")


max_price = 0
for key, values in product.items():
    price = values.get("price")
    if price > max_price:
        max_price=price

print("\nHighest price:",max_price)
print("product details with highest price:")
for  key, values in product.items():
    price = values.get("price")
    if price == max_price:
        print(f"{key}:{values}")

print("\nTotal inventory value:")
total = 0
for key, values in product.items():
    price = values.get("price")
    quantity = values.get("quantity")
    total = total+(price*quantity)
    

print(total)

laptop:{'product name': 'hp', 'price': 22000, 'quantity': 5}
mouse:{'product name': 'zebronics', 'price': 2500, 'quantity': 8}
keyboard:{'product name': 'lenova', 'price': 3500, 'quantity': 4}
monitor:{'product name': 'ausus', 'price': 6500, 'quantity': 3}
printer:{'product name': 'epson', 'price': 12000, 'quantity': 2}

Highest price: 22000
product details with highest price:
laptop:{'product name': 'hp', 'price': 22000, 'quantity': 5}

Total inventory value:
187500


In [ ]:
# Question 10

Create a dictionary of five students and their marks.

Example

    Alice : 85
    Bob : 92
    Charlie : 78
    David : 88
    Emma : 95

Write a Python program to

    Find the student with the highest marks.
    Find the student with the lowest marks.
    Calculate the average marks.
    Display students who scored more than 85.

In [73]:
student = {"alice":85,"bob":92,"charlie":78,"david":88,"emma":95}
print(student)
marks = student.values()

high = max(marks)
low = min(marks)
total = 0
n=0
for key, values in student.items():
    mark=values
    total=total+mark
    n=n+1
    if mark==high:
        print("student with highest mark:\n",f"{key}:{values}")
    if mark==low:
        print("student with lowest mark:\n",f"{key}:{values}")

print(total)
print(n)
avg=total/n
print("average marks:", avg)

print("students who scored more than 85:")
for key, values in student.items():
    mark=values
    if mark>=85:
        print(f"{key}:{values}")




{'alice': 85, 'bob': 92, 'charlie': 78, 'david': 88, 'emma': 95}
student with lowest mark:
 charlie:78
student with highest mark:
 emma:95
438
5
average marks: 87.6
students who scored more than 85:
alice:85
bob:92
david:88
emma:95
