# 3D Array

In [1]:
import numpy as np

arr = np.array([
    [
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]
    ],

    [
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]
    ],

    [
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]
    ]
])

print(arr.shape)

(3, 4, 5)


In [ ]:
# Assignment: 3D Array Indexing & Slicing

# Section A – Access Individual Elements

# Write a statement to extract:

10
24
37
43
54
66
58
49

In [9]:
print("Access element in 0 depth, 0 row, 0 column :", arr[0,0,0])
print("Access element in 0 depth, 2nd row, last column :", arr[0,2,-1])
print("Access element in 1st depth, 1st row, 2nd column :", arr[1,1,2])
print("Access element in 1st depth, 2nd row, 2nd last column :", arr[1,2,-2])
print("Access element in last depth, 0 row, last column :", arr[-1,0,-1])
print("Access element in last depth, last row, 1st column :", arr[-1,-1,1])
print("Access element in last depth, 1st row, 2nd last column :", arr[-1,1,-2])
print("Access element in 1st depth, last row, last column :", arr[1,-1,-1])


Access element in 0 depth, 0 row, 0 column : 10
Access element in 0 depth, 2nd row, last column : 24
Access element in 1st depth, 1st row, 2nd column : 37
Access element in 1st depth, 2nd row, 2nd last column : 43
Access element in last depth, 0 row, last column : 54
Access element in last depth, last row, 1st column : 66
Access element in last depth, 1st row, 2nd last column : 58
Access element in 1st depth, last row, last column : 49


In [ ]:
# Section B – Access Complete Rows

# Write a statement to extract:

1.
[15, 16, 17, 18, 19]

2.
[40, 41, 42, 43, 44]

3.
[65, 66, 67, 68, 69]

In [25]:
print("Access 1st full row in 0 depth :", arr[0,1,:])
print("Access 2nd full row in 1st depth :", arr[1,2,:])
print("Access last full row in last depth :", arr[-1,-1,:])


Access 1st full row in 0 depth : [15 16 17 18 19]
Access 2nd full row in 1st depth : [40 41 42 43 44]
Access last full row in last depth : [65 66 67 68 69]


In [ ]:
# Section C – Access Complete 2D Matrices

# Extract:

The first matrix
The second matrix
The third matrix

In [26]:
print("Access first matrix :\n", arr[0,:,:])
print("Access second matrix:\n", arr[1,:,:])
print("Access third matrix:\n", arr[-1,:,:])


Access first matrix :
 [[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
Access second matrix:
 [[30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]
Access third matrix:
 [[50 51 52 53 54]
 [55 56 57 58 59]
 [60 61 62 63 64]
 [65 66 67 68 69]]


In [ ]:
# Section D – Column Extraction
1
[10, 15, 20, 25]

2
[32, 37, 42, 47]


3
[54, 59, 64, 69]

In [29]:
print("Access 1st column in 0 depth :", arr[0,:,0])
print("Access 2nd column in 1st depth :", arr[1,:,2])
print("Access last column in last depth :", arr[-1,:,-1])


Access 1st column in 0 depth : [10 15 20 25]
Access 2nd column in 1st depth : [32 37 42 47]
Access last column in last depth : [54 59 64 69]


In [ ]:
# Section E – Slicing

Extract:

The first two matrices.
The last two matrices.
The first two rows from every matrix.
The last two rows from every matrix.
The first three columns from every matrix.
The last two columns from every matrix.

In [38]:
print("First two matrices :\n", arr[0:2,:,:])
print("Last two matrices :\n", arr[-2:,:,:])
print("First 2 rows from every matrices :\n", arr[:,0:2,:])
print("Last 2 rows from every matrices :\n", arr[:, -2:,:])
print("First 3 columns from every matrices :\n", arr[:,:,0:3])
print("Last 2 columns from every matrices :\n", arr[:,:,-2:])


First two matrices :
 [[[10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]

 [[30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]]
Last two matrices :
 [[[30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]

 [[50 51 52 53 54]
  [55 56 57 58 59]
  [60 61 62 63 64]
  [65 66 67 68 69]]]
First 2 rows from every matrices :
 [[[10 11 12 13 14]
  [15 16 17 18 19]]

 [[30 31 32 33 34]
  [35 36 37 38 39]]

 [[50 51 52 53 54]
  [55 56 57 58 59]]]
Last 2 rows from every matrices :
 [[[20 21 22 23 24]
  [25 26 27 28 29]]

 [[40 41 42 43 44]
  [45 46 47 48 49]]

 [[60 61 62 63 64]
  [65 66 67 68 69]]]
First 3 columns from every matrices :
 [[[10 11 12]
  [15 16 17]
  [20 21 22]
  [25 26 27]]

 [[30 31 32]
  [35 36 37]
  [40 41 42]
  [45 46 47]]

 [[50 51 52]
  [55 56 57]
  [60 61 62]
  [65 66 67]]]
Last 2 columns from every matrices :
 [[[13 14]
  [18 19]
  [23 24]
  [28 29]]

 [[33 34]
  [38 39]
  [43 44]
  [48 49]]

 [[53 54]
 

In [ ]:
# Section F – Advanced Slicing

[
 [10, 11, 12],
 [15, 16, 17]
]

In [39]:
print("First 2 rows, first 3 columns, in 0 depth :\n", arr[0,0:2,0:3])


First 2 rows, first 3 columns, in 0 depth :
 [[10 11 12]
 [15 16 17]]


In [ ]:
[
 [42, 43, 44],
 [47, 48, 49]
]

In [40]:
print("Last 2 rows, last 3 columns in 1st depth :\n", arr[1,-2:,-3:])


Last 2 rows, last 3 columns in 1st depth :
 [[42 43 44]
 [47 48 49]]


In [ ]:
[
 [55, 56],
 [60, 61],
 [65, 66]
]

In [42]:
print("Last 3 rows, first 2 columns in last depth :\n", arr[-1,-3:,0:2])


Last 3 rows, first 2 columns in last depth :
 [[55 56]
 [60 61]
 [65 66]]


In [ ]:
[
 [13, 14],
 [18, 19]
]

In [43]:
print("First 2 rows, last 2 columns in 0 depthj :\n", arr[0,0:2,-2:])


First 2 rows, last 2 columns in 0 depthj :
 [[13 14]
 [18 19]]


In [ ]:
# Section G –  Questions

Write a single slicing statement to extract:

Every alternate matrix.
Every alternate row from all matrices.
Every alternate column from all matrices.
The first column from every matrix.
The last column from every matrix.
The middle row from every matrix.
The middle column from every matrix.
Reverse the order of matrices.
Reverse the rows inside every matrix.
Reverse the columns inside every matrix.

In [68]:
print("Every alternate matrix :\n",arr[::2,:,:])
print("Every alternate row from all matrices :\n", arr[:,::2,:])
print("Every alternate column from all matrices :\n", arr[:,:,::2])
print("First column from every matrices :\n", arr[:,:,0])
print("Last column from every matrices :\n", arr[:,:,-1])
print ("Middle row from every matrices :\n", arr[:,arr.shape[1]//2,:])
print("Middle column from every matrices :\n", arr[:,:,arr.shape[2]//2])
print("Reverse order of matrices :\n", np.flipud(arr))
print("Reverse order of matrices :\n", arr[::-1,:,:])
print("Reverse rows inside every matrices :\n", arr[:,::-1,:])
print("Reverse columns inside every matrices :\n", arr[:,:,::-1])


Every alternate matrix :
 [[[10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]

 [[50 51 52 53 54]
  [55 56 57 58 59]
  [60 61 62 63 64]
  [65 66 67 68 69]]]
Every alternate row from all matrices :
 [[[10 11 12 13 14]
  [20 21 22 23 24]]

 [[30 31 32 33 34]
  [40 41 42 43 44]]

 [[50 51 52 53 54]
  [60 61 62 63 64]]]
Every alternate column from all matrices :
 [[[10 12 14]
  [15 17 19]
  [20 22 24]
  [25 27 29]]

 [[30 32 34]
  [35 37 39]
  [40 42 44]
  [45 47 49]]

 [[50 52 54]
  [55 57 59]
  [60 62 64]
  [65 67 69]]]
First column from every matrices :
 [[10 15 20 25]
 [30 35 40 45]
 [50 55 60 65]]
Last column from every matrices :
 [[14 19 24 29]
 [34 39 44 49]
 [54 59 64 69]]
Middle row from every matrices :
 [[20 21 22 23 24]
 [40 41 42 43 44]
 [60 61 62 63 64]]
Middle column from every matrices :
 [[12 17 22 27]
 [32 37 42 47]
 [52 57 62 67]]
Reverse order of matrices :
 [[[50 51 52 53 54]
  [55 56 57 58 59]
  [60 61 62 63 64]
  [65 66 67 68 69]]

 [[30 31 

# 2D ARRAY

In [70]:
import numpy as np

arr = np.array([
    [10, 11, 12, 13, 14, 15],
    [20, 21, 22, 23, 24, 25],
    [30, 31, 32, 33, 34, 35],
    [40, 41, 42, 43, 44, 45],
    [50, 51, 52, 53, 54, 55],
    [60, 61, 62, 63, 64, 65]
])

print(arr.shape)
print (arr[5][0])

(6, 6)
60


In [ ]:
# 2D Array Indexing & Slicing

Extract the following using a single indexing/slicing statement
1. Every alternate row

Expected Output:

[
 [10,11,12,13,14,15],
 [30,31,32,33,34,35],
 [50,51,52,53,54,55]
]

In [71]:
print("Every alternate row :\n", arr[::2,:])


Every alternate row :
 [[10 11 12 13 14 15]
 [30 31 32 33 34 35]
 [50 51 52 53 54 55]]


In [ ]:
# 2. Every alternate column

Expected Output:

[
 [10,12,14],
 [20,22,24],
 [30,32,34],
 [40,42,44],
 [50,52,54],
 [60,62,64]
]


In [72]:
print("Every alternate column :\n", arr[:,::2])


Every alternate column :
 [[10 12 14]
 [20 22 24]
 [30 32 34]
 [40 42 44]
 [50 52 54]
 [60 62 64]]


In [ ]:
3. First column

Expected Output:

[10,20,30,40,50,60]

In [73]:
print("First column :", arr[:,0])


First column : [10 20 30 40 50 60]


In [ ]:
4. Last column

Expected Output:

[15,25,35,45,55,65]

In [74]:
print("Last column :", arr[:,-1])


Last column : [15 25 35 45 55 65]


In [ ]:
5. Middle row

Expected Output:

[40,41,42,43,44,45]

In [75]:
print("Middle row :", arr[arr.shape[0]//2,:])


Middle row : [40 41 42 43 44 45]


In [ ]:
6. Middle column

Expected Output:

[13,23,33,43,53,63]

In [76]:
print("Middle column :", arr[:,arr.shape[1]//2])


Middle column : [13 23 33 43 53 63]


In [ ]:
7. First three rows

Expected Output:

[
 [10,11,12,13,14,15],
 [20,21,22,23,24,25],
 [30,31,32,33,34,35]
]


In [77]:
print("First 3 rows :\n", arr[0:3,:])


First 3 rows :
 [[10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]]


In [ ]:
8. Last three rows

Expected Output:

[
 [40,41,42,43,44,45],
 [50,51,52,53,54,55],
 [60,61,62,63,64,65]
]


In [78]:
print("Last 3 rows :\n", arr[-3:,:])


Last 3 rows :
 [[40 41 42 43 44 45]
 [50 51 52 53 54 55]
 [60 61 62 63 64 65]]


In [ ]:
9. First three columns

Expected Output:

[
 [10,11,12],
 [20,21,22],
 [30,31,32],
 [40,41,42],
 [50,51,52],
 [60,61,62]
]



In [80]:
print("First 3 columns :\n", arr[:,0:3])


First 3 columns :
 [[10 11 12]
 [20 21 22]
 [30 31 32]
 [40 41 42]
 [50 51 52]
 [60 61 62]]


In [ ]:
10. Last three columns

Expected Output:

[
 [13,14,15],
 [23,24,25],
 [33,34,35],
 [43,44,45],
 [53,54,55],
 [63,64,65]
]

In [81]:
print("Last 3 columns :\n", arr[:,-3:])


Last 3 columns :
 [[13 14 15]
 [23 24 25]
 [33 34 35]
 [43 44 45]
 [53 54 55]
 [63 64 65]]


In [ ]:
11. Reverse all rows

Expected Output:

[
 [60,61,62,63,64,65],
 [50,51,52,53,54,55],
 [40,41,42,43,44,45],
 [30,31,32,33,34,35],
 [20,21,22,23,24,25],
 [10,11,12,13,14,15]
]


In [85]:
print("Reverse all rows :\n", np.flipud(arr))
print("Reverse all rows :\n", arr[::-1,:])


Reverse all rows :
 [[60 61 62 63 64 65]
 [50 51 52 53 54 55]
 [40 41 42 43 44 45]
 [30 31 32 33 34 35]
 [20 21 22 23 24 25]
 [10 11 12 13 14 15]]
Reverse all rows :
 [[60 61 62 63 64 65]
 [50 51 52 53 54 55]
 [40 41 42 43 44 45]
 [30 31 32 33 34 35]
 [20 21 22 23 24 25]
 [10 11 12 13 14 15]]


In [ ]:
12. Reverse all columns

Expected Output:

[
 [15,14,13,12,11,10],
 [25,24,23,22,21,20],
 [35,34,33,32,31,30],
 [45,44,43,42,41,40],
 [55,54,53,52,51,50],
 [65,64,63,62,61,60]
]

In [86]:
print("Reverse all columns :\n", arr[:,::-1])


Reverse all columns :
 [[15 14 13 12 11 10]
 [25 24 23 22 21 20]
 [35 34 33 32 31 30]
 [45 44 43 42 41 40]
 [55 54 53 52 51 50]
 [65 64 63 62 61 60]]


In [ ]:
13. Reverse rows and columns simultaneously

Expected Output:


[
 [65,64,63,62,61,60],
 [55,54,53,52,51,50],
 [45,44,43,42,41,40],
 [35,34,33,32,31,30],
 [25,24,23,22,21,20],
 [15,14,13,12,11,10]
]

In [88]:
print("Reverse rows and columns simultaneously :\n", np.flip(arr))
print("Reverse rows and columns simultaneously :\n",arr[::-1,::-1])


Reverse rows and columns simultaneously :
 [[65 64 63 62 61 60]
 [55 54 53 52 51 50]
 [45 44 43 42 41 40]
 [35 34 33 32 31 30]
 [25 24 23 22 21 20]
 [15 14 13 12 11 10]]
Reverse rows and columns simultaneously :
 [[65 64 63 62 61 60]
 [55 54 53 52 51 50]
 [45 44 43 42 41 40]
 [35 34 33 32 31 30]
 [25 24 23 22 21 20]
 [15 14 13 12 11 10]]


# Write a single indexing/slicing statement to extract:


In [ ]:

[
 [22,23,24],
 [32,33,34],
 [42,43,44]
]

In [89]:
print("1,2,3 row and 2,3,4 column :\n", arr[1:4,2:5])


1,2,3 row and 2,3,4 column :
 [[22 23 24]
 [32 33 34]
 [42 43 44]]


In [ ]:
[
 [11,13,15],
 [31,33,35],
 [51,53,55]
]


In [91]:
print("alternate rows from 0 and alternate columns from 1 :\n", arr[0::2,1::2])


alternate rows from 0 and alternate columns from 1 :
 [[11 13 15]
 [31 33 35]
 [51 53 55]]


In [ ]:
[
 [40,41,42,43,44,45],
 [50,51,52,53,54,55]
]


In [93]:
print("Row 3 and 4 :\n", arr[3:5,:])
print("Row 3 and 4 :\n", arr[-3:-1,:])


Row 3 and 4 :
 [[40 41 42 43 44 45]
 [50 51 52 53 54 55]]
Row 3 and 4 :
 [[40 41 42 43 44 45]
 [50 51 52 53 54 55]]


In [ ]:
[
 [14,15],
 [24,25],
 [34,35],
 [44,45],
 [54,55],
 [64,65]
]

In [94]:
print("Last two columns :\n", arr[:,-2:])


Last two columns :
 [[14 15]
 [24 25]
 [34 35]
 [44 45]
 [54 55]
 [64 65]]
